x-database-variables: &database-variables
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
  SPRING_DATASOURCE_USERNAME: admin
  SPRING_DATASOURCE_PASSWORD: senha123

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
    ports:
      - "5431:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080

  api-client:
    build: .
    image: client-api
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      <<: *database-variables